"""Shared test infrastructure and conventions.

Testing principle: test IMDgroup code, not pymatgen.

IMDgroup-pymatgen is a thin layer over pymatgen.  When one of our
classes delegates to a pymatgen method, we do not re-test the upstream
behaviour.  Instead we test only what is ours:

- the values we compute and pass to pymatgen,
- the transformations and decisions we make around the pymatgen call,
- our own data structures, file I/O, and CLI dispatch.

This keeps the suite small and avoids coupling tests to pymatgen
internals that may move.

Where pymatgen already provides the canonical fixture or helper, reuse
it instead of maintaining a copy:

- ``pymatgen.util.testing.MatSciTest`` provides ``assert_msonable``,
  ``assert_str_content_equal``, ``serialize_with_pickle``, and an
  autouse temporary-directory fixture.  Subclass it in test classes
  that need those helpers.  Note: ``PymatgenTest`` is deprecated; use
  ``MatSciTest``.
- ``pymatgen.util.structures`` ships curated example structures.  Load
  them with ``MatSciTest.get_structure(name)`` instead of committing our
  own structure fixtures.

VASP output fixtures are generated by ``scripts/prepare_vasp_fixtures.sh``
from a real, converged run; see :func:`converged_vasp_dir` below.
"""

from __future__ import annotations

import gzip
import shutil
from pathlib import Path

import pytest


def _materialize_fixture(tmp_path: Path, name: str) -> Path:
    """Decompress a gzipped VASP fixture into *tmp_path*.

    Reads ``tests/fixtures/<name>/``, gunzips ``*.gz`` files and copies
    the plain text files.  Skips when the compressed output files are
    absent, since they are generated (not committed as plain text) by
    ``scripts/prepare_vasp_fixtures.sh``.
    """
    src = Path(__file__).parent / "fixtures" / name
    required = ("OUTCAR.gz", "vasprun.xml.gz")
    missing = [f for f in required if not (src / f).is_file()]
    if missing:
        pytest.skip(
            f"missing {name} fixture files: {', '.join(missing)}. "
            f"Run scripts/prepare_vasp_fixtures.sh <vasp-dir> {name} first."
        )
    for entry in src.iterdir():
        if entry.suffix == ".gz":
            target = tmp_path / entry.stem
            with gzip.open(entry, "rb") as fin, open(target, "wb") as fout:
                shutil.copyfileobj(fin, fout)
        else:
            shutil.copy(entry, tmp_path / entry.name)
    return tmp_path


@pytest.fixture
def converged_vasp_dir(tmp_path: Path) -> Path:
    """A converged SCF VASP run (single Li atom), decompressed to tmp."""
    return _materialize_fixture(tmp_path, "vasp_converged")


@pytest.fixture
def converged_relax_vasp_dir(tmp_path: Path) -> Path:
    """A converged relaxation run (single Na atom, ISIF=3), to tmp."""
    return _materialize_fixture(tmp_path, "vasp_converged_relax")
